<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.DependencyInjection</PackageId>
		<Title>Myth Dependency Injection Library</Title>
		<Authors>Paula Leal</Authors>
		<Company>Myth</Company>
		<PackageIcon>myth-dependency-injection-logo.png</PackageIcon>
		<Description>Type discovery and convention-based service registration with automatic assembly scanning, interface mapping, and plugin architecture support for simplified dependency injection configuration.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>dotnet;dependency-injection;ioc;container;assembly-scanning;convention;auto-registration;plugin-architecture;myth</PackageTags>
		<!-- Docs -->
		<RepositoryUrl>https://github.com/paulaolileal/myth/tree/main/Myth.DependencyInjection</RepositoryUrl>
		<PackageProjectUrl>https://github.com/paulaolileal/myth/tree/main/Myth.DependencyInjection</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="myth-dependency-injection-logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
	</ItemGroup>

</Project>
