<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Platforms>x64</Platforms>
		<Version>2.0.0.10</Version>
		<Authors>Paulo Leal</Authors>
		<Description>The components of dependency injection from myth</Description>
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth-commons</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth-commons</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
		<PackageId>Myth.DependencyInjection</PackageId>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
	</ItemGroup>

</Project>
