<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Repository.EntityFramework</PackageId>
		<Title>Myth Repository Entity Framework Implementation</Title>
		<Authors>Paula Leal</Authors>
		<Company>Myth</Company>
		<PackageIcon>myth-repository-ef-logo.png</PackageIcon>
		<Description>Entity Framework Core implementations of repository pattern with Unit of Work, specification support, expression handling, and transaction management for robust data access with EF Core.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>dotnet;entity-framework;ef-core;repository-pattern;unit-of-work;data-access;orm;transactions;myth</PackageTags>
		<!-- Docs -->
		<RepositoryUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Repository.EntityFramework</RepositoryUrl>
		<PackageProjectUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Repository.EntityFramework</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="myth-repository-ef-logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Repository\Myth.Repository.csproj" />
		<ProjectReference Include="..\Myth.Specification\Myth.Specification.csproj" />
		<ProjectReference Include="..\Myth.DependencyInjection\Myth.DependencyInjection.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
	</ItemGroup>

</Project>
