<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Repository.EntityFramework</PackageId>
		<Authors>Paula Leal</Authors>
		<PackageIcon>Logo.jpg</PackageIcon>
		<Description>It is a .NET library for defining database access repositories using Entity Framework.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<!-- Docs -->
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.Repository.EntityFramework</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.Repository.EntityFramework</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Logo.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Repository\Myth.Repository.csproj" />
		<ProjectReference Include="..\Myth.Specification\Myth.Specification.csproj" />
		<ProjectReference Include="..\Myth.DependencyInjection\Myth.DependencyInjection.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.6" />
	</ItemGroup>

</Project>
