stages:
  - build
  - test
  - publish
  
default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  NUGET_API_KEY: $NUGET_API_KEY
  NUGET_API_URL: $NUGET_API_URL

build-job:
  stage: build
  script:
    - dotnet build --configuration Release
  only:
    - tags

test-job:
  stage: test
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install --global dotnet-coverage
    - dotnet test --filter FullyQualifiedName!~Rest --logger trx --results-directory "Coverage" --configuration Release --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - dotnet-coverage merge *.cobertura.xml --recursive --output merged.cobertura.xml --output-format cobertura
  artifacts:
    paths:
      - merged.cobertura.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: merged.cobertura.xml
  only:
    - tags
  dependencies:
    - build-job

publish-job:
  stage: publish
  script:
    - PACKAGE_VERSION=$(echo "$CI_COMMIT_TAG" | cut -d "v" -f2- )
    - for project in $(ls **/*.csproj | grep -v 'Test.csproj$'); do
        dotnet pack $project --configuration Release --output nupkgs /p:PackageVersion=${PACKAGE_VERSION};
      done
    - dotnet nuget push "nupkgs/*.nupkg" --source $NUGET_API_URL --api-key $NUGET_API_KEY;
  only:
    - tags
  dependencies:
    - build-job
    - test-job