stages:
  - build
  - test
  - publish

variables:
  NUGET_API_URL: "https://api.nuget.org/v3/index.json" # Substitua pela URL da sua API NuGet se necessário
  NUGET_API_KEY: $NUGET_API_KEY # Defina esta variável no GitLab CI/CD environment variables

default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

build-job:
  stage: build
  script:
    - dotnet build --configuration Release
  artifacts:
    paths:
      - /**/*.dll

test-job:
  stage: test
  script:
    - dotnet test --no-build
  dependencies:
    - build-job

publish-job:
  stage: publish
  script:
    - for project in $(ls **/*.csproj); do
        dotnet pack $project --configuration Release --no-build --output nupkgs /p:PackageVersion=${CI_COMMIT_TAG};
        dotnet nuget push "nupkgs/*.nupkg" --source $NUGET_API_URL --api-key $NUGET_API_KEY;
      done
  only:
    - tags
  dependencies:
    - build-job
    - test-job