<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Flow</PackageId>
		<Title>Myth Flow Pipeline Library</Title>
		<Authors>Paula Leal</Authors>
		<Company>Myth</Company>
		<PackageIcon>myth-flow-logo.png</PackageIcon>
		<Description>Fluent pipeline orchestration with Result pattern, OpenTelemetry integration, retry policies, and global service provider support for building robust data processing workflows.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>dotnet;pipeline;flow;orchestration;result-pattern;opentelemetry;retry;data-processing;fluent-api;myth</PackageTags>
		<!-- Docs -->
		<RepositoryUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Flow</RepositoryUrl>
		<PackageProjectUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Flow</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="myth-flow-logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
