<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Platforms>x64</Platforms>
		<Version>2.0.0.9</Version>
		<Authors>Paulo Leal</Authors>
		<Description>The interfaces declaration of generic repositories using expressions and specifications</Description>
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth-commons</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth-commons</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
		<PackageId>Myth.Repository</PackageId>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Specification\Myth.Specification.csproj" />
	</ItemGroup>

</Project>
