<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>x64</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Repository</PackageId>
		<Authors>Paula Leal</Authors>
		<PackageIcon>Logo.jpg</PackageIcon>
		<Description>It is a .NET library for defining database access repositories.</Description>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
		<!-- Docs -->
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.Repository</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.Repository</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\Logo.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
		<ProjectReference Include="..\Myth.Specification\Myth.Specification.csproj" />
	</ItemGroup>

</Project>
