<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Repository</PackageId>
		<Authors>Paula Leal</Authors>
		<PackageIcon>myth-repository-logo.png</PackageIcon>
		<Description>Generic repository pattern interfaces with async support, specification integration, and pagination. Provides read/write separation, CRUD operations, and extensible repository contracts for clean data access architecture.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<!-- Docs -->
		<RepositoryUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Repository</RepositoryUrl>
		<PackageProjectUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Repository</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="ValueObjects\**" />
	  <EmbeddedResource Remove="ValueObjects\**" />
	  <None Remove="ValueObjects\**" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<None Include="myth-repository-logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
		<ProjectReference Include="..\Myth.Specification\Myth.Specification.csproj" />
	</ItemGroup>

</Project>
