<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>x64</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.DependencyInjection.Providers</PackageId>
		<Authors>Paula Leal</Authors>
		<PackageIcon>Logo.jpg</PackageIcon>
		<Description>It is a .NET library to perform dependency injection for pre-configured third-party libraries.</Description>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
		<!-- Docs -->
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.DependencyInjection.Providers</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.DependencyInjection.Providers</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.DependencyInjection\Myth.DependencyInjection.csproj" />
		<ProjectReference Include="..\Myth.Repository\Myth.Repository.csproj" />
	</ItemGroup>


	<ItemGroup>
		<None Include="..\Logo.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
