<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Platforms>x64</Platforms>
		<Version>2.0.0.16</Version>
		<Authors>Paula Leal</Authors>
		<Description>The dependency injection of third part libraries</Description>
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth-commons</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth-commons</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
		<PackageId>Myth.DependencyInjection.Providers</PackageId>
		<PackageIcon>Logo.jpg</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.DependencyInjection\Myth.DependencyInjection.csproj" />
		<ProjectReference Include="..\Myth.Repository\Myth.Repository.csproj" />
	</ItemGroup>


	<ItemGroup>
		<None Include="..\Logo.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
