using System.Collections.Concurrent;
using Myth.Interfaces;

namespace Myth.Morph;

/// <summary>
/// Thread-safe registry for <see cref="IMorphAutoMapper"/> instances generated by Myth.Morph.Generator.
/// Consulted by <see cref="BaseMappingExecutor{TDestination}"/> before the reflection-based fallback,
/// enabling zero-reflection auto-mapping when the generator is present.
/// </summary>
public static class MorphAutoMapperRegistry {
	private static readonly ConcurrentDictionary<(Type Source, Type Destination), IMorphAutoMapper> _mappers = new( );

	/// <summary>
	/// Registers a generated auto-mapper for a source/destination pair.
	/// Typically called from a <c>[ModuleInitializer]</c> in generated code.
	/// </summary>
	public static void Register( IMorphAutoMapper mapper ) {
		ArgumentNullException.ThrowIfNull( mapper );
		_mappers[ (mapper.SourceType, mapper.DestinationType) ] = mapper;
	}

	/// <summary>
	/// Attempts to retrieve the registered mapper for the given source/destination pair.
	/// Returns <c>false</c> when no generated mapper exists — the caller should fall back to reflection.
	/// </summary>
	public static bool TryGet( Type sourceType, Type destinationType, out IMorphAutoMapper? mapper )
		=> _mappers.TryGetValue( (sourceType, destinationType), out mapper );

	/// <summary>Clears all registered mappers. For testing purposes only.</summary>
	internal static void Clear( ) => _mappers.Clear( );
}
