<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Specification</PackageId>
		<Title>Myth Specification Pattern Library</Title>
		<Authors>Paula Leal</Authors>
		<Company>Myth</Company>
		<PackageIcon>myth-specification-logo.png</PackageIcon>
		<Description>Query specification pattern for encapsulating business rules in readable, composable, and testable specifications. Supports filtering, sorting, pagination, and conditional logic for clean query construction.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>dotnet;specification-pattern;query;business-rules;filtering;sorting;pagination;ddd;clean-architecture;myth</PackageTags>
		<!-- Docs -->
		<RepositoryUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Specification</RepositoryUrl>
		<PackageProjectUrl>https://github.com/paulaolileal/myth/tree/main/Myth.Specification</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="myth-specification-logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
	</ItemGroup>

</Project>
