<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Patform -->
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<!-- Settings -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<!-- Package -->
		<PackageId>Myth.Flow.Actions</PackageId>
		<Authors>Paula Leal</Authors>
		<PackageIcon>Logo.jpg</PackageIcon>
		<Description>A fluent .NET library extension for Myth.Flow library with CQRS/Event-driven architecture with dispatcher, event bus, and message brokers</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<!-- Docs -->
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.Flow</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth/-/tree/main/Myth.Flow</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.11.1" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
		<PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\Logo.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Myth.Flow\Myth.Flow.csproj" />
	  <ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Myth.Flow.Actions.Test" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" PublicKey="0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7" />
	</ItemGroup>

</Project>
