using System.Text;
using Myth.Morph.Generator.Models;

namespace Myth.Morph.Generator.Emitters;

/// <summary>
/// Emits the C# source code for a concrete <c>IMorphAutoMapper</c> implementation
/// that maps same-name, type-compatible properties from source to destination
/// using direct assignments — zero reflection at runtime.
/// </summary>
internal static class AutoMapperEmitter {

	/// <summary>
	/// Generates the full source code for the auto-mapper class described by <paramref name="model"/>.
	/// </summary>
	/// <param name="model">The mapping pair model to generate code for.</param>
	/// <returns>The generated C# source as a string.</returns>
	public static string Emit( MorphableTypeModel model ) {
		var sb = new StringBuilder( );

		sb.AppendLine( "// <auto-generated/>" );
		sb.AppendLine( "#nullable enable" );
		sb.AppendLine( );
		sb.AppendLine( "namespace Myth.Morph.Generated;" );
		sb.AppendLine( );
		sb.AppendLine( $"[global::System.CodeDom.Compiler.GeneratedCode(\"Myth.Morph.Generator\", \"1.0.0\")]" );
		sb.AppendLine( $"internal sealed class {model.AutoMapperClassName} : global::Myth.Interfaces.IMorphAutoMapper {{" );

		// ── SourceType / DestinationType properties ───────────────────────────
		sb.AppendLine( $"\tpublic global::System.Type SourceType => typeof( {model.SourceTypeFullName} );" );
		sb.AppendLine( $"\tpublic global::System.Type DestinationType => typeof( {model.DestinationTypeFullName} );" );
		sb.AppendLine( );

		// ── MapProperties method ──────────────────────────────────────────────
		sb.AppendLine( "\tpublic void MapProperties( object sourceObj, object destinationObj, global::System.Collections.Generic.HashSet<string> skip ) {" );
		sb.AppendLine( $"\t\tvar source = ( {model.SourceTypeFullName} )sourceObj;" );
		sb.AppendLine( $"\t\tvar dest   = ( {model.DestinationTypeFullName} )destinationObj;" );

		if ( model.Properties.IsEmpty ) {
			sb.AppendLine( "\t\t// No auto-mappable same-name properties found for this pair." );
		} else {
			sb.AppendLine( );
			foreach ( var prop in model.Properties )
				EmitPropertyAssignment( sb, prop );
		}

		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );

		return sb.ToString( );
	}

	// ─── Private helpers ─────────────────────────────────────────────────────────

	private static void EmitPropertyAssignment( StringBuilder sb, PropertyMappingModel prop ) {
		if ( prop.RequiresNullCheck ) {
			// Nullable source → non-nullable dest: guard against null to avoid InvalidOperationException.
			// The property is skipped entirely when source value is null (consistent with AssignDefault
			// behavior in the reflection path for reference types).
			sb.AppendLine(
				$"\t\tif ( !skip.Contains( \"{prop.Name}\" ) && source.{prop.Name} is not null ) " +
				$"dest.{prop.Name} = source.{prop.Name}!;" );
		} else {
			sb.AppendLine(
				$"\t\tif ( !skip.Contains( \"{prop.Name}\" ) ) dest.{prop.Name} = source.{prop.Name};" );
		}
	}
}
