using System.Collections.Immutable;
using System.Text;
using Myth.Morph.Generator.Models;

namespace Myth.Morph.Generator.Emitters;

/// <summary>
/// Emits the <c>MorphBootstrap</c> class and the <c>[ModuleInitializer]</c> method
/// that wire all generated auto-mappers and schema registrations into the Myth.Morph runtime
/// before <c>AddMorph()</c> is called.
/// </summary>
/// <remarks>
/// The <c>[ModuleInitializer]</c> runs once when the assembly is loaded and:
/// <list type="number">
///   <item>Registers every generated <c>IMorphAutoMapper</c> into <see cref="Myth.Morph.MorphAutoMapperRegistry"/>.</item>
///   <item>Registers a <c>MorphBootstrap</c> instance into <see cref="Myth.Morph.GeneratedBootstrapRegistry"/>
///         so that <c>AddMorph()</c> can skip assembly scanning entirely.</item>
/// </list>
/// The <c>MorphBootstrap.Register(registry)</c> method calls
/// <c>registry.RegisterInstanceBasedMapping</c> for every discovered pair,
/// enabling the schema-based mapping system to resolve these types.
/// </remarks>
internal static class BootstrapEmitter {

	/// <summary>
	/// Generates the full source code for the bootstrap and module initializer classes.
	/// </summary>
	/// <param name="models">All unique mapping pairs discovered in the compilation.</param>
	/// <returns>The generated C# source as a string.</returns>
	public static string Emit( ImmutableArray<MorphableTypeModel> models ) {
		var sb = new StringBuilder( );

		sb.AppendLine( "// <auto-generated/>" );
		sb.AppendLine( "#nullable enable" );
		sb.AppendLine( );
		sb.AppendLine( "namespace Myth.Morph.Generated;" );
		sb.AppendLine( );

		EmitBootstrapClass( sb, models );
		sb.AppendLine( );
		EmitModuleInitializer( sb, models );

		return sb.ToString( );
	}

	// ─── MorphBootstrap class ────────────────────────────────────────────────────

	private static void EmitBootstrapClass(
		StringBuilder sb,
		ImmutableArray<MorphableTypeModel> models ) {

		sb.AppendLine( "[global::System.CodeDom.Compiler.GeneratedCode(\"Myth.Morph.Generator\", \"1.0.0\")]" );
		sb.AppendLine( "internal sealed class MorphBootstrap : global::Myth.Interfaces.IMorphRegistrationBootstrap {" );
		sb.AppendLine( );
		sb.AppendLine( "\t/// <summary>" );
		sb.AppendLine( "\t/// Registers schema-level mappings for all types discovered by Myth.Morph.Generator." );
		sb.AppendLine( "\t/// Called by <see cref=\"Myth.Extensions.ServiceCollectionExtensions.AddMorph\"/> during DI setup." );
		sb.AppendLine( "\t/// </summary>" );
		sb.AppendLine( "\tpublic void Register( global::Myth.Morph.SchemaRegistry registry ) {" );

		foreach ( var model in models ) {
			sb.AppendLine(
				$"\t\tregistry.RegisterInstanceBasedMapping( " +
				$"typeof( {model.SourceTypeFullName} ), " +
				$"typeof( {model.DestinationTypeFullName} ) );" );
		}

		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );
	}

	// ─── MorphModuleInitializer class ────────────────────────────────────────────

	private static void EmitModuleInitializer(
		StringBuilder sb,
		ImmutableArray<MorphableTypeModel> models ) {

		sb.AppendLine( "[global::System.CodeDom.Compiler.GeneratedCode(\"Myth.Morph.Generator\", \"1.0.0\")]" );
		sb.AppendLine( "internal static class MorphModuleInitializer {" );
		sb.AppendLine( );
		sb.AppendLine( "\t/// <summary>" );
		sb.AppendLine( "\t/// Runs automatically when the assembly is loaded." );
		sb.AppendLine( "\t/// Registers all generated auto-mappers and the bootstrap into the Myth.Morph runtime." );
		sb.AppendLine( "\t/// </summary>" );
		sb.AppendLine( "\t[global::System.Runtime.CompilerServices.ModuleInitializer]" );
		sb.AppendLine( "\tpublic static void Initialize( ) {" );

		foreach ( var model in models ) {
			sb.AppendLine(
				$"\t\tglobal::Myth.Morph.MorphAutoMapperRegistry.Register( new {model.AutoMapperClassName}( ) );" );
		}

		sb.AppendLine( );
		sb.AppendLine( "\t\tglobal::Myth.Morph.GeneratedBootstrapRegistry.Register( new MorphBootstrap( ) );" );
		sb.AppendLine( "\t}" );
		sb.AppendLine( "}" );
	}
}
