using Myth.Morph;

namespace Myth.Interfaces;

/// <summary>
/// Contract implemented by code generated by Myth.Morph.Generator.
/// Registers all IMorphableTo and IMorphableFrom mappings discovered at compile time,
/// replacing assembly scanning in <see cref="Myth.Extensions.ServiceCollectionExtensions.AddMorph"/>.
/// </summary>
public interface IMorphRegistrationBootstrap {
	/// <summary>
	/// Registers all generated type mappings into the provided <see cref="SchemaRegistry"/>.
	/// Called during <c>AddMorph()</c> when generated bootstrap is detected.
	/// </summary>
	void Register( SchemaRegistry registry );
}
