namespace Myth.Interfaces;

/// <summary>
/// Contract implemented by code generated by Myth.Morph.Generator.
/// Provides compile-time property mapping that replaces reflection in
/// <see cref="Myth.Morph.BaseMappingExecutor{TDestination}.AutoMapProperties"/>.
/// </summary>
/// <remarks>
/// The generated implementation maps same-name properties with direct assignments,
/// skipping any property listed in the <c>skip</c> set (already bound manually or ignored).
/// </remarks>
public interface IMorphAutoMapper {
	/// <summary>The source type this mapper reads from.</summary>
	Type SourceType { get; }

	/// <summary>The destination type this mapper writes to.</summary>
	Type DestinationType { get; }

	/// <summary>
	/// Maps same-name compatible properties from <paramref name="source"/> to <paramref name="destination"/>,
	/// skipping any property name present in <paramref name="skip"/>.
	/// </summary>
	/// <param name="source">The source object to read values from.</param>
	/// <param name="destination">The destination object to write values to.</param>
	/// <param name="skip">Property names to skip — already manually bound or explicitly ignored.</param>
	void MapProperties( object source, object destination, HashSet<string> skip );
}
