<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Myth</RootNamespace>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Platforms>x64</Platforms>
		<Version>2.0.0.6</Version>
		<Authors>Paulo Leal</Authors>
		<Description>Common functions for all myth projects</Description>
		<RepositoryUrl>https://gitlab.com/dotnet-myth/myth-commons</RepositoryUrl>
		<PackageProjectUrl>https://gitlab.com/dotnet-myth/myth-commons</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
		<PackageId>Myth.Commons</PackageId>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.SmartEnum" Version="2.0.1" />
		<PackageReference Include="AutoMapper" Version="11.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.15" />
	</ItemGroup>
</Project>
