<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Platforms>x64</Platforms>
    <Version>1.0.0.8-stage-01</Version>
    <Authors>Paulo Leal</Authors>
    <Description>Common functions for all myth projects</Description>
    <RepositoryUrl>https://gitlab.com/harpy-framework/harpy</RepositoryUrl>
    <PackageProjectUrl>https://gitlab.com/harpy-framework/harpy</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
    <PackageId>Myth.Commons</PackageId>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\logo.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>