using FluentAssertions;
using Microsoft.Extensions.DependencyInjection;
using Myth.Extensions;
using Myth.Flow.Actions.Extensions;
using Myth.Flow.Actions.Test.Models;
using Myth.Interfaces;
using Myth.Models;
using Myth.ServiceProvider;
using NSubstitute;

namespace Myth.Flow.Actions.Test;

/// <summary>
/// Tests for PipelineExtensions cache functionality
/// </summary>
public class PipelineExtensionsCacheTests : IDisposable {
	private readonly ICacheProvider _cacheProvider;
	private readonly IServiceProvider _serviceProvider;

	public PipelineExtensionsCacheTests( ) {
		// Create mock before registering services
		_cacheProvider = Substitute.For<ICacheProvider>( );

		var services = new ServiceCollection( );
		services.AddLogging( );
		services.AddFlow( );
		services.AddFlowActions( options => {
			options.UseInMemory( )
				   .ScanAssemblies( typeof( TestQueryHandler ).Assembly );
		} );

		// Replace the cache provider with our mock
		services.AddSingleton<ICacheProvider>( _cacheProvider );

		_serviceProvider = services.BuildServiceProvider( );
		MythServiceProvider.Initialize( _serviceProvider );
	}

	public void Dispose( ) {
		MythServiceProvider.Reset( );
		( _serviceProvider as IAsyncDisposable )?.DisposeAsync( );
		( _serviceProvider as IDisposable )?.Dispose( );
	}

	[Fact]
	public async Task Query_WithAutoGeneratedCache_ShouldCreateDifferentKeysForDifferentQueries( ) {
		// Arrange
		var capturedKeys = new List<string>( );

		_cacheProvider.When( x => x.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ) )
			.Do( callInfo => capturedKeys.Add( callInfo.ArgAt<string>( 0 ) ) );
		_cacheProvider.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ).ReturnsForAnyArgs( CacheValue<string>.Miss( ) );

		var query1 = new TestQuery { Key = "test-key-1" };
		var query2 = new TestQuery { Key = "test-key-2" };

		// Act
		var result1 = await PipelineExtensions
			.Start( query1 )
			.Query<TestQuery, string>( ( query, conf ) => conf.UseCache( ) )
			.ExecuteAsync( );

		var result2 = await PipelineExtensions
			.Start( query2 )
			.Query<TestQuery, string>( ( query, conf ) => conf.UseCache( ) )
			.ExecuteAsync( );

		// Assert
		result1.IsSuccess.Should( ).BeTrue( );
		result2.IsSuccess.Should( ).BeTrue( );

		capturedKeys.Should( ).HaveCount( 2 );
		capturedKeys[ 0 ].Should( ).NotBe( capturedKeys[ 1 ] );
		capturedKeys[ 0 ].Should( ).StartWith( "TestQuery:" );
		capturedKeys[ 1 ].Should( ).StartWith( "TestQuery:" );
	}

	[Fact]
	public async Task Query_WithCustomKeyGenerator_ShouldUseProvidedFunction( ) {
		// Arrange
		var capturedKey = string.Empty;

		_cacheProvider.When( x => x.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ) )
			.Do( callInfo => capturedKey = callInfo.ArgAt<string>( 0 ) );
		_cacheProvider.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ).ReturnsForAnyArgs( CacheValue<string>.Miss( ) );

		var query = new TestQuery { Key = "test-key" };

		// Act
		var result = await PipelineExtensions
			.Start( query )
			.Query<TestQuery, string>( ( q, conf ) => conf.UseCache<TestQuery>( q => $"weather-forecast-{q.Key}" ) )
			.ExecuteAsync( );

		// Assert
		result.IsSuccess.Should( ).BeTrue( );
		capturedKey.Should( ).Be( "weather-forecast-test-key" );
	}

	[Fact]
	public async Task Query_WithExplicitCacheKey_ShouldUseProvidedKey( ) {
		// Arrange
		var capturedKey = string.Empty;

		_cacheProvider.When( x => x.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ) )
			.Do( callInfo => capturedKey = callInfo.ArgAt<string>( 0 ) );
		_cacheProvider.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ).ReturnsForAnyArgs( CacheValue<string>.Miss( ) );

		var query = new TestQuery { Key = "test-key" };

		// Act
		var result = await PipelineExtensions
			.Start( query )
			.Query<TestQuery, string>( ( q, conf ) => conf.UseCache( "static-cache-key" ) )
			.ExecuteAsync( );

		// Assert
		result.IsSuccess.Should( ).BeTrue( );
		capturedKey.Should( ).Be( "static-cache-key" );
	}

	[Fact]
	public async Task Query_WithoutCacheConfiguration_ShouldNotUseCache( ) {
		// Arrange
		var query = new TestQuery { Key = "test-key" };

		// Act
		var result = await PipelineExtensions
			.Start( query )
			.Query<TestQuery, string>( )
			.ExecuteAsync( );

		// Assert
		result.IsSuccess.Should( ).BeTrue( );

		// Verify cache was never accessed
		await _cacheProvider.DidNotReceive( ).GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) );
		await _cacheProvider.DidNotReceive( ).SetAsync( Arg.Any<string>( ), Arg.Any<string>( ), Arg.Any<TimeSpan>( ), Arg.Any<bool>( ), Arg.Any<CancellationToken>( ) );
	}

	[Fact]
	public async Task Query_WithCacheHit_ShouldReturnCachedValue( ) {
		// Arrange
		_cacheProvider.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ).ReturnsForAnyArgs( CacheValue<string>.Hit( "cached-result" ) );

		var query = new TestQuery { Key = "test-key" };

		// Act
		var result = await PipelineExtensions
			.Start( query )
			.Query<TestQuery, string>( ( q, conf ) => conf.UseCache( "cache-key" ) )
			.ExecuteAsync( );

		// Assert
		result.IsSuccess.Should( ).BeTrue( );
		result.Value.Should( ).Be( "cached-result" );
	}

	[Fact]
	public async Task Query_WithCacheTtlAndSliding_ShouldConfigureCorrectly( ) {
		// Arrange
		var capturedTtl = TimeSpan.Zero;
		var capturedSliding = false;

		_cacheProvider.GetAsync<string>( Arg.Any<string>( ), Arg.Any<CancellationToken>( ) ).ReturnsForAnyArgs( CacheValue<string>.Miss( ) );

		_cacheProvider.SetAsync(
			Arg.Any<string>( ),
			Arg.Any<string>( ),
			Arg.Do<TimeSpan>( ttl => capturedTtl = ttl ),
			Arg.Do<bool>( sliding => capturedSliding = sliding ),
			Arg.Any<CancellationToken>( ) )
			.Returns( Task.CompletedTask );

		var query = new TestQuery { Key = "test-key" };

		// Act
		var result = await PipelineExtensions
			.Start( query )
			.Query<TestQuery, string>( ( q, conf ) => conf
				.UseCache( "cache-key" )
				.WithTtl( TimeSpan.FromMinutes( 15 ) )
				.WithSlidingExpiration( true ) )
			.ExecuteAsync( );

		// Assert
		result.IsSuccess.Should( ).BeTrue( );
		capturedTtl.Should( ).Be( TimeSpan.FromMinutes( 15 ) );
		capturedSliding.Should( ).BeTrue( );
	}
}