<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Myth</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Platforms>x64</Platforms>
    <Version>2.0.0.0-stage-01</Version>
    <Authors>Paulo Leal</Authors>
    <Description>A simple OData implementation separating database entities and view models</Description>
    <RepositoryUrl>https://gitlab.com/dotnet-myth/myth-commons</RepositoryUrl>
    <PackageProjectUrl>https://gitlab.com/dotnet-myth/myth-commons</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageOutputPath>$(AppData)/NuGet/Packages</PackageOutputPath>
    <PackageId>Myth.OData</PackageId>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myth.Commons\Myth.Commons.csproj" />
    <ProjectReference Include="..\Myth.Specification\Myth.Specification.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
  </ItemGroup>

</Project>
